### ISSUE TITLE
[Epic] Full Delta Lake Integration

### ISSUE THREAD

**Issue by shehabgamin** [lakehq/sail#171]
### Milestone 1: Core Table Operations
- [x] Basic Read (Snapshot Isolation)
- [x] Basic Write (Append & Overwrite modes)
- [x] Partitioned Writes
- [x] Data Skipping (Partition Pruning & File Statistics)
- [x] Schema Handling (Validation & Evolution)
- [x] Time Travel (By Version & Timestamp)
### Milestone 2: Core Log & File Types
- [x] JSON Commits
- [x] Parquet Checkpoint (V1)
- [x] V2 Checkpoint 
- [ ] Multi-part Checkpoints (Deprecated)
- [x] Log Compaction Files
- [x] Last Checkpoint File
- [x] Version Checksum File

### Milestone 3: DML Operations
- [x] DELETE (Copy-on-Write)
- [x] MERGE INTO (Copy-on-Write)
- [ ] UPDATE
- [ ] Merge-on-Read (Writing Deletion Vectors)

### Milestone 4: Table Management & Protocol
- [ ] Transaction Control (Conflict Detection & ACID)
- [x] Log Cleanup (Expired Metadata Removal)
- [x] Column Mapping (Id & Name modes)
- [ ] Constraints (Invariants & Check Constraints)
- [ ] VACUUM (Physical Data File Removal)
- [ ] OPTIMIZE (Bin-packing & Z-Ordering)
- [ ] RESTORE
- [ ] Change Data Feed
- [ ] Identity Columns & Generated Columns & Default Columns
- [ ] Variant Data Type
- [x] TimeStampNtz
- [x] In-Commit Timestamps
- [x] Append-Only Tables
- [ ] Delection Vectors
- [ ] Row Tracking
- [x] Type Widening
- [ ] Clustered Table
- [ ] VACUUM Protocol Check

### Milestone 6: Ecosystem & Streaming
- [x] Unity Catalog Integration
- [ ] AWS Glue / Hive Metastore Integration
- [ ] Catalog-managed Table 
- [ ] Iceberg Compat V1/V2
- [ ] Streaming Read (Tail Log)
- [ ] Streaming Write (Sink)

Other Milestones to be mentioned later.

## Related Work
- https://github.com/lakehq/sail/pull/578
- https://github.com/lakehq/sail/pull/634
- https://github.com/lakehq/sail/pull/677
- https://github.com/lakehq/sail/pull/680
- https://github.com/lakehq/sail/pull/717
- https://github.com/lakehq/sail/pull/723
- https://github.com/lakehq/sail/pull/750
- https://github.com/lakehq/sail/pull/768
- https://github.com/lakehq/sail/pull/794
- https://github.com/lakehq/sail/pull/837
- https://github.com/lakehq/sail/pull/848
- https://github.com/lakehq/sail/pull/854
- https://github.com/lakehq/sail/pull/856
- https://github.com/lakehq/sail/pull/916
- https://github.com/lakehq/sail/pull/921

**Comment by shehabgamin** [comment]
@lonless9 Are the completed milestones up to date?

**Comment by lonless9** [comment]
@shehabgamin Yeah it's up to date now.

**Comment by keen85** [comment]
@lonless9, 
Yesterday I found out that currently sail is not able to read Delta Tables if it is partitioned and one of the partition columns is of type `TimestampType`. Is this a known limitation?

**Comment by lonless9** [comment]
> sail is not able to read Delta Tables if it is partitioned and one of the partition columns is of type TimestampType. 

@keen85 ,
I will reproduce this issue and find a solution! It looks like caused by the default logic of `arrow-cast` not handling delta-style timestamps correctly. Coincidentally I have a cleanup plan for this recently, and Iceberg timestamp will be taken into consideration as well. 

Could you share more details? For example, what kind of error would be thrown, or is the query result style incorrect?

Besides, I've drafted a PR #1095 for this based on my current thinking. And it would be great to learn your thoughts!

Thanks for the feedback!

**Comment by keen85** [comment]
Are **`generated columns`** also something that you would consider for the roadmap?
These are caluclated columns where the generation logic is defined by some Spark SQL expression that is executed on _write_ operations.
- https://docs.delta.io/delta-batch/#use-generated-columns
- https://delta.io/blog/2023-04-12-delta-lake-generated-columns/


Generated columns can also be used as partition column. When working with large amounts of transactional data that carry some transaction TIMESTAMP column, it is handy to have a generated/calculated partition column that will make sure not to overpartition (e.g. `CAST(DATE_TRUNC('YEAR', some_timestamp) AS DATE)`).
JVM-Spark also uses the generation expression for query optimizing / partition pruning. So that when a table is partitioned by a generated column that uses `some_timestamp` and  there is a filter predicate on `some_timestamp`, only the relevant partitions will be scanned.
- https://delta.io/blog/pros-cons-hive-style-partionining/#:~:text=Using%20a%20generated%20column%20to%20partition%20time%20series%20data

**Comment by lonless9** [comment]
@keen85  Excellent suggestion! You can see that compared to Iceberg, Delta's current roadmap focuses more on DML/DDL, but in reality, both need to consider their own features along with DML/DDL. We will update the roadmap soon!

**Comment by the-lazy-val** [comment]
@lonless9 i would like to take a look at HMS/Hive integration, please lmk if that's ok
thanks!

**Comment by linhr** [comment]
> [@lonless9](https://github.com/lonless9) i would like to take a look at HMS/Hive integration, please lmk if that's ok thanks!

@the-lazy-val Thanks for your interest in contributing to Sail! Basic HMS support is already part of our Delta Lake integration. (We haven't marked the task as fully complete yet.) Our focus right now is to improve our code architecture and support/improve advanced features that require deep interaction between lakehouse data sources and the catalog (e.g., catalog-managed commits). As our internals are under rapid development, we don't quite yet have concrete tasks for community contributions.

If you're interested in Delta Lake and HMS, you could try out Sail in your settings and identify feature gaps or parity issues where the behavior diverges from the Delta Lake Java implementation. Such "stress tests" and bug reports are extremely valuable to us!
