### ISSUE TITLE
Implement the MVP for distributed processing

### ISSUE THREAD

**Issue by linhr** [lakehq/sail#246]
## User Interface
- [x] Sail CLI (#245)
- [x] Sail configuration (#279)

## Core Functionalities
- [x] Distributed processing setup (#244)
- [x] Distributed job stages and shuffle (#265)
- [x] Worker scaling and reuse (part of #280)

## Resource Provider Integration
- [x] Kubernetes resource provider (#280)
- [ ] ~~YARN resource provider~~ (out of scope for MVP)

## Observability
- [ ] ~~OpenTelemetry setup for driver/worker nodes~~ (out of scope for MVP)

**Comment by shehabgamin** [comment]
There are these PRs as well:
- Implement actor system ([#264](https://github.com/lakehq/sail/pull/264)).
- Improve actor error handling ([#263](https://github.com/lakehq/sail/pull/263)).
- Improve actor implementation ([#262](https://github.com/lakehq/sail/pull/262)).
- Implement physical plan extension codec ([#259](https://github.com/lakehq/sail/pull/259)).

**Comment by shehabgamin** [comment]
- https://github.com/lakehq/sail/pull/286
- https://github.com/lakehq/sail/pull/287
- https://github.com/lakehq/sail/pull/288
- https://github.com/lakehq/sail/pull/289
- https://github.com/lakehq/sail/pull/292

**Comment by shehabgamin** [comment]
- https://github.com/lakehq/sail/pull/302
- https://github.com/lakehq/sail/pull/316
- https://github.com/lakehq/sail/pull/319

**Comment by linhr** [comment]
The MVP is completed in the Sail 0.2.0 release. The following tasks will be tackled in future releases:
* ~~#321~~
* #298
* #322

**Comment by bcncpp** [comment]
how much of this work is needed? Do you have a epoch roadmap?

**Comment by linhr** [comment]
> how much of this work is needed? Do you have a epoch roadmap?

@bcncpp ~~I'm not sure if I understand the question. Could you elaborate?~~ Are you referring to the remaining tasks after the MVP?

We don't have a timeline for these yet. We'll assess the scope and design based on user requests.
